---
- name: Aptos Installer
  hosts: aptos

  tasks:
    - name: Install required packages
      become: yes
      apt:
        update_cache: yes
        name:
          - git

    - name: Clone Aptos
      git:
        repo: 'https://github.com/aptos-labs/aptos-core.git'
        dest: ~/aptos-core

    - name: Run dev-setup script
      shell: 'cd ~/aptos-core/ && ./scripts/dev_setup.sh -b -v'

    - name: Checkout to devnet branch
      shell: 'cd ~/aptos-core/ && git checkout origin/devnet'

    - name: Copy public_full_node
      copy:
        src: ~/aptos-core/config/src/config/test_data/public_full_node.yaml
        dest: ~/aptos-core/public_full_node.yaml
        remote_src: yes

    - name: Download genesis
      get_url:
        url: 'https://devnet.aptoslabs.com/genesis.blob'
        dest: ~/aptos-core/genesis.blob

    - name: Download waypoint
      get_url:
        url: 'https://devnet.aptoslabs.com/waypoint.txt'
        dest: ~/aptos-core/waypoint.txt

    - name: Patch datadir
      replace:
        path: ~/aptos-core/public_full_node.yaml
        regexp: '(\s*data_dir:).*$'
        replace: '\1 "HOME/aptos-data"'

    - name: Patch genesis
      replace:
        path: ~/aptos-core/public_full_node.yaml
        regexp: '(\s*genesis_file_location:).*$'
        replace: '\1 "HOME/aptos-core/genesis.blob"'

    - name: Patch HOME
      replace:
        path: ~/aptos-core/public_full_node.yaml
        regexp: 'HOME'
        replace: "{{ ansible_facts['env']['HOME'] }}"

    - name: Paste waypoint file
      shell: 'DATA=$(cat ~/aptos-core/waypoint.txt); sed -i -e "s/0:01234567890ABCDEFFEDCA098765421001234567890ABCDEFFEDCA0987654210/$DATA/" ~/aptos-core/public_full_node.yaml'

    - name: Build node
      shell: 'source ~/.cargo/env && cd ~/aptos-core && cargo build -p aptos-node --release'
      args:
        executable: /bin/bash
        creates: ~/aptos-core/target/release/aptos-node

    - name: Render service file
      template:
        src: aptos.service
        dest: /etc/systemd/system/aptos.service
      become: yes

    - name: Start aptos service
      become: yes
      systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: aptos
